name: Compile script

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  compile:
    name: Compile autohotkey script
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build with latest AutoHotkey release
        uses: benmusson/ahk2exe-action@d779a7d7b2b3dcb238b8ad8bdbca986cf4f75356 # v1.2.0
        with:
          in: hotkeys.ahk
          out: out/hotkeys-${{ github.ref_name }}.exe
          target: x64
          compression: upx
          ahk-tag: v2.0.19
          ahk2exe-tag: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload executable as artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          name: hotkeys-${{ github.ref_name }}.exe
          path: out/hotkeys-${{  github.ref_name }}.exe

      - name: Create release and attach executable
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: out/hotkeys-${{  github.ref_name }}.exe
          draft: true
          generate_release_notes: true
